WIP: Add prime tester to accumulator
LayerXcom/verified-vyper-contracts pull request #74
Opened 2019-01-21 17:33 UTC by hskang9

- What I did

resolve #73 

I have confirmed that this can also be checked for bigger number than 2**64 from original.
I may extend this to have:

- bigger number testing(so far less than 2**256)
- solve easy answers(2,3,5,7)
- Resolve Fermat liars if they exist

- Cute Animal Picture

![pic](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB3lX8ShQ3B8ddnThV_pWgwWF1bajHmC37mqH-bwG-pHPIM_E4TQ)

2019-01-21 23:48 UTC, nrryuya requested changes

2019-01-21 23:48 UTC, nrryuya commented on contracts/accumulator/isPrime.vy
> +    for i in range(M_LIST_LENGTH):
I got this error here ;)
```
line 8: Range only accepts literal (constant) values
    for i in range(M_LIST_LENGTH):
-------------------^
```

2019-01-22 00:01 UTC, nrryuya commented
@hskang9 
Thank you! A few comments.
- Could you rebase to the latest master branch and create a new PR? This inlined version is WIP and I think it'd be better to have a new directory and file `contracts/prime/isPrime.vy` because this contract can be used as stand-alone.
- Tests are always necessary ;) Please add tests at `tests/prime/test_isPrime.py`.

2019-01-22 03:34 UTC, nrryuya commented
@hskang9 
About tests, I'll prepare `BigInt.vy` which can be used by `isPrime.vy`.

2019-01-22 13:36 UTC, hskang9 commented
Thank you! @nrryuya now that I have Big integer operations in separate file, I can focus on the tester. I will create WIP to master branch based on the comments received 👍

2019-01-22 13:36 UTC, hskang9 commented
Closing this for new PR

2019-01-22 13:36 UTC, closed without merging

2019-01-22 14:08 UTC, nrryuya commented
@hskang9 
#79 is still WIP so it's OK to wait for my work or to prepare only test cases (without actually executing them) ;)

2019-01-22 17:13 UTC, hskang9 commented
I think I will put TODO in comment to remove big integer operations after ```BigInt.vy``` is developed.

2019-01-26 14:42 UTC, hskang9 commented
This PR is now moved to #81